#!/bin/sh

uci -q delete firewall.l2tpipsecserver

uci -q del_list web.ruleset_main.rules=l2tpipsecservermodal
uci -q delete web.l2tpipsecservermodal
uci -q delete web.l2tpipsecservercard

uci -q delete firewall.vpn

for item in `uci show firewall | grep "'vpn'" | cut -f1,2 -d. | awk '{a[i++]=$0} END {for (j=i-1; j>=0;) print a[j--] }'`
do
	uci -q delete $item
done

/etc/init.d/firewall restart 2>/dev/null

exit 0