#!/bin/sh

. $IPKG_INSTROOT/lib/functions.sh

#/etc/uci-defaults/80-l2tp-ipsec-server

uci -q batch <<-EOT
	delete firewall.l2tpipsecserver
	set firewall.l2tpipsecserver=include
	set firewall.l2tpipsecserver.type=script
	set firewall.l2tpipsecserver.path=/lib/functions/firewall-l2tp-ipsec-server.sh
	set firewall.l2tpipsecserver.reload=1
	commit firewall
EOT

# Disable the xl2tpd package which is controlled by l2tpipsecserver.
# Otherwise it would start at every boot regardless of l2tp server state.
/etc/init.d/xl2tpd disable

#/etc/uci-defaults/conf-web-add-l2tp-ipsec-server

uci -q del_list web.ruleset_main.rules=l2tpipsecservermodal
uci add_list web.ruleset_main.rules=l2tpipsecservermodal

uci -q delete web.l2tpipsecservermodal
uci set web.l2tpipsecservermodal=rule
uci set web.l2tpipsecservermodal.target=/modals/l2tp-ipsec-server-modal.lp

uci add_list web.l2tpipsecservermodal.roles=admin
uci add_list web.l2tpipsecservermodal.roles=engineer # not present in the original uci-default
uci add_list web.l2tpipsecservermodal.roles=superuser

uci -q delete web.l2tpipsecserver_card
uci set web.l2tpipsecserver_card=card
uci set web.l2tpipsecserver_card.card=014_l2tp-ipsec-server.lp
uci set web.l2tpipsecserver_card.modal=l2tpipsecservermodal


#/etc/uci-defaults/tch_0090-vpn

# l2tp user passwords + ipsec PSK
. /lib/functions/l2tp-ipsec-secrets.sh

generate_and_install_chap_secret() {
  local user="$1"
  uci_set "vpn" "${user}" "password" "$(generate_chap_secret)"
}

generate_and_install_ipsec_PSK() {
  uci_set "ipsec" "l2tp" "pre_shared_key" "$(generate_ipsec_PSK)"
}

config_load "vpn"

config_foreach generate_and_install_chap_secret l2tp_user
generate_and_install_ipsec_PSK

# network + firewall
add_firewall_zone() {

  local vpn_remote_ip_start vpn_remote_ip_end

  config_get vpn_remote_ip_start l2tpipsecserver remote_ip_start
  config_get vpn_remote_ip_end l2tpipsecserver remote_ip_end

  # default value for vpn subnet is 192.168.0.0/16
  vpn_subnet="192.168.0.0/16"
  if [ -n "${vpn_remote_ip_start}" -a -n "${vpn_remote_ip_end}" ]; then
    vpn_subnet="${vpn_remote_ip_start}-${vpn_remote_ip_end}"
  fi

  uci set firewall.$1=zone
  uci set firewall.$1.name="$1"
  uci set firewall.$1.input='ACCEPT'
  uci set firewall.$1.output='ACCEPT'
  uci set firewall.$1.forward='ACCEPT'
  uci set firewall.$1.wan='0'
  uci set firewall.$1.masq='0'
  uci set firewall.$1.mtu_fix='1'
  uci set firewall.$1.device='ppp+'
  uci set firewall.$1.subnet="${vpn_subnet}"
}

add_firewall_forwarding() {
  uci add firewall forwarding > /dev/null
  uci set firewall.@forwarding[-1].src="$1"
  uci set firewall.@forwarding[-1].dest="$2"
}

add_firewall_zone vpn
add_firewall_forwarding lan vpn
add_firewall_forwarding vpn lan
add_firewall_forwarding vpn wan

# Save all config changes
uci commit


/etc/init.d/nginx restart
/etc/init.d/transformer restart

/etc/init.d/l2tp-ipsec-server enable
/etc/init.d/l2tp-ipsec-server start 2>/dev/null
/etc/init.d/ipsec enable

exit 0
