#!/bin/sh
#
# Startup/Stop script for aMuled - aMule Daemon
#


case "$1" in

'start')
PATH=/usr/local/bin:/usr/bin:/bin /usr/bin/amuled -f -c /tmp/run/mountd/sda1/sharing/config/amule
;;

'stop')
killall -9 amuled
killall -9 amuleweb
echo "aMule Stopped"
;;

*)
echo "Usage: /etc/init.d/amule { start | stop }"
;;

esac
