#!/bin/sh /etc/rc.common

if [ -d /tmp/run/mountd/sda1 ]; then
   echo "OK USB Found"
   else
       if [ -d /mnt/usb/* ] ; then
          echo "Link to usb"
          sda1=$(ls /mnt/usb/)
          mkdir -p /tmp/run/mountd/
          ln -s /mnt/usb/$sda1 /tmp/run/mountd/sda1
          else
              exit 1
       fi
fi
