#!/bin/sh /etc/rc.common
START=98
STOP=02
USE_PROCD=1
PROG=/usr/bin/lua
start_service() {
    procd_open_instance shim
    procd_set_param command $PROG /dumaos/ctwatch-shim.lua
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
