#!/bin/sh /etc/rc.common
# (C) NETDUMA Software 2022

START=99
STOP=10
PROG=/usr/bin/fq-codel-add-filter
USE_PROCD=1

start_service() {
  chmod +x "$PROG"
  procd_open_instance
  procd_set_param command "$PROG"
  procd_set_param respawn
}
