#!/bin/sh
#
# Startup/Stop script for Aria2 - Aria2 Daemon
#


CONF=/mnt/usb/USB-A1/sharing/config/aria2/aria2.conf

case "$1" in

'start')
aria2c --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all --daemon=true --conf-path=$CONF
echo "Aria2 Started"
;;

'stop')
killall -9 aria2c
echo "Aria2 Stopped"
;;

*)
echo "Usage: /etc/init.d/aria2 { start | stop }"
;;

esac
